<a href="https://colab.research.google.com/github/anaraquelslv/inteligencia-artificial-umc/blob/main/numpy_scipy_pandas_matplotlib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Crie um array unidimensional de 50 elementos contendo números inteiros aleatórios entre 10 e 100.

In [1]:

import numpy as np

array_aleatorio = np.random.randint(10, 101, size=50)

print(array_aleatorio)

[ 11  56  38  80  12  22  58  42  22  77  47  37  12  23  53  31  36  87
  39  34  43  58  34  24  10  39  12  94  44  60  63  92  52  25  90  19
  27  59  36  72  46  90  86 100  47  94  20  43  37  73]


Gere uma matriz 4x4 com números inteiros de 1 a 16 e extraia a ultima linha.

In [6]:
import numpy as np

matriz = np.arange(1, 17).reshape(4, 4)

print("Matriz 4x4 original:")
print(matriz)
print()


ultima_linha = matriz[-1]

print("Última linha extraída:")
print(ultima_linha)

Matriz 4x4 original:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Última linha extraída:
[13 14 15 16]


Crie um array de zeros com comprimento 15 e substitua os valores da 5ª à 10ª posição por 1.

In [7]:
import numpy as np

array_zeros = np.zeros(15, dtype=int)

print("Array original:")
print(array_zeros)

array_zeros[4:10] = 1

print("\nArray modificado:")
print(array_zeros)

Array original:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

Array modificado:
[0 0 0 0 1 1 1 1 1 1 0 0 0 0 0]


Gere um array de 100 números inteiros aleátorios e encontre a mediana e a moda dos valores.

In [8]:
import numpy as np
from scipy import stats


array_cem = np.random.randint(1, 21, size=100)

mediana = np.median(array_cem)


resultado_moda = stats.mode(array_cem, keepdims=False)


valor_moda = resultado_moda.mode
contagem_moda = resultado_moda.count

print(f"Array gerado:\n{array_cem}\n")
print(f"Mediana: {mediana}")
print(f"Moda: O número {valor_moda} apareceu {contagem_moda} vezes.")

Array gerado:
[19  6 11  9 14 16 11 18 13  1  2 19  7  8 10  3 12  4  8 12 17 19 20  7
  4 13 18  9 15 10 19  7  8 19 14  4  8 13  1 20  9 18 15 15 20 19 13 13
  1 15 16 19 19 10  8  4 18  3 14 10 13 11 10 12  7 19 12  8 11  9  3  7
 17 13 15 20 15  9  7  9  2 15 16 20 16 10 15  2  9 19 12 11  1  9 12 12
  9  9 17 14]

Mediana: 12.0
Moda: O número 9 apareceu 10 vezes.


Crie um array de 20 elementos contendo números entre 1 e 100 e substitua todos os valores múltiplos de 3 por -3.

In [9]:
import numpy as np

array_numeros = np.random.randint(1, 101, size=20)

print("Array original:")
print(array_numeros)


array_numeros[array_numeros % 3 == 0] = -3

print("\nArray modificado:")
print(array_numeros)

Array original:
[68 88 37 39 25 26 76 70 96 19 53 27 62 57 61 75  1 14 51 15]

Array modificado (múltiplos de 3 viraram -3):
[68 88 37 -3 25 26 76 70 -3 19 53 -3 62 -3 61 -3  1 14 -3 -3]


Gere uma matriz 5x5 de números aleatórios entre 0 e 1 e encontre a soma de cada coluna

In [10]:
import numpy as np

matriz = np.random.rand(5, 5)

print("Matriz 5x5 original:")

print(np.round(matriz, 2))


soma_colunas = np.sum(matriz, axis=0)

print("\nSoma de cada coluna:")
print(np.round(soma_colunas, 2))

Matriz 5x5 original:
[[0.34 0.61 0.9  0.34 0.43]
 [0.53 0.07 0.38 0.71 0.08]
 [0.63 0.34 0.41 0.59 0.08]
 [0.76 0.02 0.63 0.62 0.15]
 [0.86 0.13 0.84 0.19 0.13]]

Soma de cada coluna:
[3.12 1.17 3.15 2.47 0.86]


Crie dois arrays de números aleatórios e encontre a correlação entre eles.

In [11]:
import numpy as np

array_a = np.random.rand(50)
array_b = np.random.rand(50)

matriz_correlacao = np.corrcoef(array_a, array_b)

print("Matriz de Correlação Completa:")
print(np.round(matriz_correlacao, 4))
print()

valor_correlacao = matriz_correlacao[0, 1]

print(f"A correlação entre os dois arrays é: {valor_correlacao:.4f}")

Matriz de Correlação Completa:
[[ 1.    -0.057]
 [-0.057  1.   ]]

A correlação entre os dois arrays é: -0.0570


Gere uma matriz 3x3 com números inteiros aleatórios e eleve todos os seus elementos ao quadrado.

In [12]:
import numpy as np

matriz_original = np.random.randint(1, 11, size=(3, 3))

print("Matriz 3x3 Original:")
print(matriz_original)
print()

matriz_quadrado = matriz_original ** 2

print("Matriz com elementos ao quadrado:")
print(matriz_quadrado)

Matriz 3x3 Original:
[[3 8 4]
 [5 5 4]
 [8 9 9]]

Matriz com elementos ao quadrado:
[[ 9 64 16]
 [25 25 16]
 [64 81 81]]


Crie um array com 10 números aleatórios e normalize seus valores entre 0 e 1.

In [13]:
import numpy as np

array_original = np.random.randint(1, 101, size=10)

print("Array original:")
print(array_original)
print()


valor_min = array_original.min()
valor_max = array_original.max()

array_normalizado = (array_original - valor_min) / (valor_max - valor_min)

print("Array normalizado (entre 0 e 1):")
print(np.round(array_normalizado, 4))

Array original:
[14 31 80 80 65 77 26 40  3 21]

Array normalizado (entre 0 e 1):
[0.1429 0.3636 1.     1.     0.8052 0.961  0.2987 0.4805 0.     0.2338]


Crie uma matriz identidade 6x6 e substitua a diagonal principal por valores crescentes de 1 a 6.

In [14]:
import numpy as np

matriz_identidade = np.eye(6, dtype=int)

print("Matriz Identidade original:")
print(matriz_identidade)
print()


valores_crescentes = np.arange(1, 7)


np.fill_diagonal(matriz_identidade, valores_crescentes)

print("Matriz com a diagonal substituída:")
print(matriz_identidade)

Matriz Identidade original:
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]

Matriz com a diagonal substituída:
[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


Gere um array de 100 números inteiros e encontre o valor que mais se repete no array.

In [15]:
import numpy as np

array_numeros = np.random.randint(1, 21, size=100)

valores_unicos, contagens = np.unique(array_numeros, return_counts=True)

indice_maior_contagem = np.argmax(contagens)

valor_mais_frequente = valores_unicos[indice_maior_contagem]
quantidade = contagens[indice_maior_contagem]

print(f"O valor que mais se repete é o {valor_mais_frequente}.")
print(f"Ele apareceu {quantidade} vezes no array.")

O valor que mais se repete é o 2.
Ele apareceu 8 vezes no array.


Crie uma matriz 4x4 e substitua os valores da diagonal principal por 7.

In [16]:
import numpy as np

matriz = np.zeros((4, 4), dtype=int)

print("Matriz original:")
print(matriz)
print()

np.fill_diagonal(matriz, 7)

print("Matriz com a diagonal alterada:")
print(matriz)

Matriz original:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Matriz com a diagonal alterada:
[[7 0 0 0]
 [0 7 0 0]
 [0 0 7 0]
 [0 0 0 7]]


Crie um array contendo os 10 primeiros números pares e calcule sua soma cumulativa.

In [18]:
import numpy as np

pares = np.arange(2, 22, 2)

print("Array original com os 10 primeiros números pares:")
print(pares)
print()

soma_acumulada = np.cumsum(pares)

print("Array com a soma cumulativa:")
print(soma_acumulada)

Array original com os 10 primeiros números pares:
[ 2  4  6  8 10 12 14 16 18 20]

Array com a soma cumulativa:
[  2   6  12  20  30  42  56  72  90 110]


Calcule a diferença entre dois arrays de números aleatórios de mesmo comprimento e encontre a média das diferenças.

In [17]:
import numpy as np

array_a = np.random.randint(1, 51, size=10)
array_b = np.random.randint(1, 51, size=10)

print("Array A:")
print(array_a)
print()

print("Array B:")
print(array_b)
print()

diferencas = array_a - array_b

print("Array de diferenças (A - B):")
print(diferencas)
print()

media_diferencas = np.mean(diferencas)

print("Média das diferenças:")
print(media_diferencas)

Array A:
[20  2 22 38  8 28 45 16 40 33]

Array B:
[22  6 13 18  3 27 11 46 38  7]

Array de diferenças (A - B):
[ -2  -4   9  20   5   1  34 -30   2  26]

Média das diferenças:
6.1


Gere um array contendo 20 números e substitua todos os valores maiores que 50 por 50.

In [19]:
import numpy as np

numeros = np.random.randint(1, 101, size=20)

print("Array original:")
print(numeros)
print()

numeros[numeros > 50] = 50

print("Array modificado (teto máximo de 50):")
print(numeros)

Array original:
[94 31 88 31 74 26 32 29  8 92 19  6 17 55  4  7 61  8 95 77]

Array modificado (teto máximo de 50):
[50 31 50 31 50 26 32 29  8 50 19  6 17 50  4  7 50  8 50 50]


Crie um array unidimensional e reorganize seus valores em uma matriz 3x4.

In [20]:
import numpy as np

array_1d = np.arange(1, 13)

print("Array unidimensional original:")
print(array_1d)
print()

matriz_3x4 = array_1d.reshape(3, 4)

print("Matriz 3x4 remodelada:")
print(matriz_3x4)

Array unidimensional original:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Matriz 3x4 remodelada:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Gere uma matriz 4x4 de números inteiros aleatórios e multiplique cada valor por sua posição na matriz

In [21]:
import numpy as np

matriz_valores = np.random.randint(1, 11, size=(4, 4))

print("Matriz de valores aleatórios:")
print(matriz_valores)
print()

matriz_posicoes = np.arange(16).reshape(4, 4)

print("Matriz de posições (índices de 0 a 15):")
print(matriz_posicoes)
print()

resultado = matriz_valores * matriz_posicoes

print("Resultado da multiplicação:")
print(resultado)

Matriz de valores aleatórios:
[[ 9  4  5  5]
 [ 7  8 10  7]
 [ 4  1  2  5]
 [ 3  8  8  7]]

Matriz de posições (índices de 0 a 15):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Resultado da multiplicação:
[[  0   4  10  15]
 [ 28  40  60  49]
 [ 32   9  20  55]
 [ 36 104 112 105]]


Crie um array de 10 elementos contendo números entre 1 e 100 e substitua todos os valores múltiplos de 5 por 0.

In [23]:
import numpy as np

array_numeros = np.random.randint(1, 101, size=10)

print("Array original:")
print(array_numeros)
print()

array_numeros[array_numeros % 5 == 0] = 0

print("Array modificado:")
print(array_numeros)

Array original:
[82 32 17 85 71 76 79 40  4 21]

Array modificado:
[82 32 17  0 71 76 79  0  4 21]


Crie dois arrays de números inteiros aleatórios de tamanho 20 e calcule o ângulo entre eles (produto escalar normalizado).

In [24]:
import numpy as np

array_a = np.random.randint(1, 11, size=20)
array_b = np.random.randint(1, 11, size=20)

print("Array A:")
print(array_a)
print()

print("Array B:")
print(array_b)
print()

produto_escalar = np.dot(array_a, array_b)

norma_a = np.linalg.norm(array_a)
norma_b = np.linalg.norm(array_b)

cosseno = produto_escalar / (norma_a * norma_b)

cosseno_ajustado = np.clip(cosseno, -1.0, 1.0)

angulo_radianos = np.arccos(cosseno_ajustado)

angulo_graus = np.degrees(angulo_radianos)

print(f"Cosseno calculado: {cosseno_ajustado:.4f}")
print(f"O angulo entre os vetores e de {angulo_graus:.2f} graus")

Array A:
[ 2 10 10  6  6  1 10  7  5  4  1 10  6 10  5  3  9 10  1  1]

Array B:
[ 1  6  1  8  8 10  6  4  9  6  4  4  7  6  9  9  7  4  6  6]

Cosseno calculado: 0.7545
O angulo entre os vetores e de 41.01 graus


Crie uma matriz de números inteiros e encontre o valor mínimo de cada linha.

In [25]:
import numpy as np

matriz = np.random.randint(1, 100, size=(4, 5))

print("Matriz original (4 linhas e 5 colunas):")
print(matriz)
print()

minimos_linhas = np.min(matriz, axis=1)

print("Valor mínimo de cada linha:")
print(minimos_linhas)

Matriz original (4 linhas e 5 colunas):
[[62 17 35 72 74]
 [ 3 62 91 83 72]
 [83 46 50 99 84]
 [52 57  8  3 66]]

Valor mínimo de cada linha:
[17  3 46  3]


Calcule a integral da função $f(x) = x^2 \sin(x)$ no intervalo de 0 a $\pi$.

In [26]:
import numpy as np
from scipy import integrate

def funcao_f(x):
    return (x ** 2) * np.sin(x)

limite_inferior = 0
limite_superior = np.pi

resultado_completo = integrate.quad(funcao_f, limite_inferior, limite_superior)

valor_integral = resultado_completo[0]
erro_estimado = resultado_completo[1]

print("Resultado do calculo da integral:")
print(valor_integral)
print()

print("Erro estimado da operacao:")
print(erro_estimado)

Resultado do calculo da integral:
5.869604401089359

Erro estimado da operacao:
6.516569951530559e-14


Resolva a equação diferencial $dy/dx = x - y$, com $y(0) = 1$, no intervalo de $0$ a $10$.

In [27]:
import numpy as np
from scipy import integrate

def equacao_diferencial(x, y):
    return x - y

intervalo = (0, 10)

y_inicial = [1]

pontos_x = np.linspace(0, 10, 11)

resultado = integrate.solve_ivp(equacao_diferencial, intervalo, y_inicial, t_eval=pontos_x)

print("Valores de X avaliados:")
print(resultado.t)
print()

print("Resultados de Y calculados para cada X:")
print(resultado.y[0])

Valores de X avaliados:
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

Resultados de Y calculados para cada X:
[1.         0.73592162 1.27061569 2.09941711 3.03671724 4.01363119
 5.00467394 6.00210836 7.00078371 8.0001898  9.00046149]


 Encontre as raízes da função $f(x) = x^4 - 3x^3 + 2$ utilizando SciPy.

In [28]:
import numpy as np
from scipy import optimize

def funcao_f(x):
    return (x ** 4) - (3 * (x ** 3)) + 2

chutes_iniciais = [-2, 0, 2, 4]

raizes_brutas = optimize.fsolve(funcao_f, chutes_iniciais)

raizes_arredondadas = np.round(raizes_brutas, 4)

raizes_unicas = np.unique(raizes_arredondadas)

print("Raízes reais únicas encontradas:")
print(raizes_unicas)

Raízes reais únicas encontradas:
[1.     2.9196]


Use a função de otimização de SciPy para maximizar $f(x) = -x^2 + 4x + 1$.

In [29]:
import numpy as np
from scipy import optimize

def funcao_invertida(x):
    return -(-(x ** 2) + (4 * x) + 1)

chute_inicial = [0.0]

resultado = optimize.minimize(funcao_invertida, chute_inicial)

x_maximo = resultado.x[0]

valor_maximo_y = -resultado.fun

print("Coordenada X onde ocorre o ponto máximo:")
print(np.round(x_maximo, 4))
print()

print("Valor máximo alcançado pela função original:")
print(np.round(valor_maximo_y, 4))

Coordenada X onde ocorre o ponto máximo:
2.0

Valor máximo alcançado pela função original:
5.0


Calcule a transformada de Fourier de um sinal composto de $\sin(2\pi t)$ e $\cos(4\pi t)$.

In [31]:
import numpy as np
from scipy import fft

quantidade_amostras = 500
espacamento = 1.0 / quantidade_amostras

tempo = np.linspace(0.0, 1.0, quantidade_amostras, endpoint=False)

sinal_misto = np.sin(2 * np.pi * tempo) + np.cos(4 * np.pi * tempo)

resultado_fft_complexo = fft.fft(sinal_misto)

magnitude_frequencias = np.abs(resultado_fft_complexo)

regua_frequencias = fft.fftfreq(quantidade_amostras, espacamento)

frequencias_positivas = regua_frequencias[:quantidade_amostras//2]
magnitudes_positivas = magnitude_frequencias[:quantidade_amostras//2]

limiar_deteccao = 50
indices_picos = np.where(magnitudes_positivas > limiar_deteccao)

print("Frequências dominantes encontradas no sinal (em Hz):")
print(np.round(frequencias_positivas[indices_picos], 2))

Frequências dominantes encontradas no sinal (em Hz):
[1. 2.]


Encontre a matriz inversa de uma matriz 5x5 de números aleatórios.

In [32]:
import numpy as np
from scipy import linalg

matriz_original = np.random.randint(1, 10, size=(5, 5))

print("Matriz original (5x5):")
print(matriz_original)
print()

matriz_inversa = linalg.inv(matriz_original)

print("Matriz inversa:")
print(np.round(matriz_inversa, 3))

Matriz original (5x5):
[[2 8 6 2 2]
 [8 8 4 6 3]
 [4 3 8 5 5]
 [4 8 9 1 4]
 [8 1 1 5 9]]

Matriz inversa:
[[-0.39   0.179 -0.061  0.24  -0.046]
 [ 0.236 -0.013 -0.104 -0.063  0.038]
 [-0.16   0.006  0.117  0.12  -0.085]
 [ 0.198  0.029  0.159 -0.284 -0.016]
 [ 0.228 -0.174 -0.036 -0.061  0.166]]


Use a função de interpolação cúbica de SciPy para interpolar os dados $(0, 0), (1, 2), (2, 3), (3, 5), (4, 4)$.

In [33]:
import numpy as np
from scipy import interpolate

x_original = np.array([0, 1, 2, 3, 4])
y_original = np.array([0, 2, 3, 5, 4])

interpolador_cubico = interpolate.CubicSpline(x_original, y_original)

x_novo_denso = np.linspace(0, 4, 10)

y_calculado = interpolador_cubico(x_novo_denso)

print("Novos pontos em X (incluindo valores intermediários):")
print(np.round(x_novo_denso, 2))
print()

print("Valores de Y calculados pela curva cúbica:")
print(np.round(y_calculado, 2))

Novos pontos em X (incluindo valores intermediários):
[0.   0.44 0.89 1.33 1.78 2.22 2.67 3.11 3.56 4.  ]

Valores de Y calculados pela curva cúbica:
[0.   1.24 1.89 2.27 2.68 3.42 4.4  5.14 5.17 4.  ]


Resolva o sistema de equações $3x + 2y = 5$ e $x + 4y = 6$.

In [34]:
import numpy as np
from scipy import linalg

matriz_a = np.array([[3, 2], [1, 4]])

vetor_b = np.array([5, 6])

resultado = linalg.solve(matriz_a, vetor_b)

valor_x = resultado[0]
valor_y = resultado[1]

print("O valor de X é:")
print(valor_x)
print()

print("O valor de Y é:")
print(valor_y)

O valor de X é:
0.7999999999999999

O valor de Y é:
1.3


Ajuste uma curva quadrática aos pontos $(1, 2), (2, 4), (3, 5), (4, 7), (5, 8)$.

In [35]:
import numpy as np
from scipy import optimize

def modelo_quadratico(x, a, b, c):
    return (a * (x ** 2)) + (b * x) + c

eixo_x = np.array([1, 2, 3, 4, 5])
eixo_y = np.array([2, 4, 5, 7, 8])

coeficientes, matriz_covariancia = optimize.curve_fit(modelo_quadratico, eixo_x, eixo_y)

valor_a = coeficientes[0]
valor_b = coeficientes[1]
valor_c = coeficientes[2]

print("Coeficientes ideais encontrados:")
print()

print(f"Valor de a: {np.round(valor_a, 4)}")
print(f"Valor de b: {np.round(valor_b, 4)}")
print(f"Valor de c: {np.round(valor_c, 4)}")

Coeficientes ideais encontrados:

Valor de a: -0.0714
Valor de b: 1.9286
Valor de c: 0.2


Calcule a integral dupla da função $f(x,y) = xy + x^2$ no intervalo $[0, 2]$ para $x$ e $[0, 1]$ para $y$.

In [36]:
from scipy import integrate

def funcao_f(y, x):
    return (x * y) + (x ** 2)

limite_x_inferior = 0
limite_x_superior = 2

limite_y_inferior = lambda x: 0
limite_y_superior = lambda x: 1

resultado_completo = integrate.dblquad(funcao_f, limite_x_inferior, limite_x_superior, limite_y_inferior, limite_y_superior)

valor_integral = resultado_completo[0]
erro_estimado = resultado_completo[1]

print("Resultado do cálculo da integral dupla:")
print(valor_integral)
print()

print("Erro estimado da operação:")
print(erro_estimado)

Resultado do cálculo da integral dupla:
3.666666666666667

Erro estimado da operação:
5.5294392329864537e-14


Encontre os autovalores e autovetores de uma matriz 4x4 de números inteiros aleatórios.

In [37]:
import numpy as np
from scipy import linalg

matriz_original = np.random.randint(1, 11, size=(4, 4))

autovalores, autovetores = linalg.eig(matriz_original)

print("Matriz original (4x4):")
print(matriz_original)
print()

print("Autovalores encontrados:")
print(np.round(autovalores, 3))
print()

print("Autovetores (cada coluna é um autovetor):")
print(np.round(autovetores, 3))

Matriz original (4x4):
[[7 4 4 2]
 [3 2 6 7]
 [4 6 5 6]
 [2 3 9 8]]

Autovalores encontrados:
[19.959+0.j     5.265+0.j    -1.612+1.279j -1.612-1.279j]

Autovetores (cada coluna é um autovetor):
[[ 0.399+0.j     0.885+0.j     0.099+0.173j  0.099-0.173j]
 [ 0.471+0.j    -0.152+0.j     0.127-0.426j  0.127+0.426j]
 [ 0.529+0.j    -0.013+0.j    -0.665+0.j    -0.665-0.j   ]
 [ 0.583+0.j    -0.439+0.j     0.54 +0.169j  0.54 -0.169j]]


Resolva a equação $e^x - x^2 = 0$ para encontrar a raiz mais próxima de $x = 1$.

In [38]:
import numpy as np
from scipy import optimize

def equacao_exponencial(x):
    return np.exp(x) - (x ** 2)

chute_inicial = [1.0]

raiz_encontrada = optimize.fsolve(equacao_exponencial, chute_inicial)

print("A raiz real encontrada a partir de x = 1 é:")
print(np.round(raiz_encontrada[0], 4))

A raiz real encontrada a partir de x = 1 é:
-0.7035


Calcule o determinante de uma matriz 6x6 de números aleatórios entre -10 e 10.

In [39]:
import numpy as np
from scipy import linalg

matriz = np.random.randint(-10, 11, size=(6, 6))

determinante_bruto = linalg.det(matriz)

determinante_limpo = np.round(determinante_bruto, 2)

print("Matriz original 6x6:")
print(matriz)
print()

print("O determinante da matriz é:")
print(determinante_limpo)

Matriz original 6x6:
[[  0  -2   5  -2  10   8]
 [  2  -4   4  10   4   1]
 [ -3  -2   0   5   6   0]
 [  9   0   9   2  -1   9]
 [ -3   0   6  10 -10   9]
 [  7   5   5   5   7  -2]]

O determinante da matriz é:
-155705.0


Utilize a função de otimização multivariada para minimizar $f(x, y) = (x-2)^2 + (y-3)^2$.

In [40]:
import numpy as np
from scipy import optimize

def funcao_multivariada(vars):
    x = vars[0]
    y = vars[1]
    return ((x - 2) ** 2) + ((y - 3) ** 2)

chute_inicial = [0.0, 0.0]

resultado = optimize.minimize(funcao_multivariada, chute_inicial)

coordenadas_minimas = resultado.x
valor_minimo_funcao = resultado.fun

print("Coordenadas que minimizam a função (X, Y):")
print(np.round(coordenadas_minimas, 4))
print()

print("O valor mínimo alcançado pela função:")
print(np.round(valor_minimo_funcao, 4))

Coordenadas que minimizam a função (X, Y):
[2. 3.]

O valor mínimo alcançado pela função:
0.0


Calcule a transformada de Fourier inversa de um sinal complexo gerado aleatoriamente.

In [41]:
import numpy as np
from scipy import fft

quantidade_amostras = 8

parte_real = np.random.rand(quantidade_amostras)
parte_imaginaria = np.random.rand(quantidade_amostras) * 1j

sinal_frequencia = parte_real + parte_imaginaria

sinal_tempo_reconstruido = fft.ifft(sinal_frequencia)

print("Sinal original (Domínio da Frequência):")
print(np.round(sinal_frequencia, 2))
print()

print("Sinal reconstruído (Domínio do Tempo):")
print(np.round(sinal_tempo_reconstruido, 2))

Sinal original (Domínio da Frequência):
[0.19+0.51j 0.8 +0.46j 0.32+0.49j 0.75+0.92j 0.48+0.57j 0.5 +0.21j
 0.09+0.4j  0.96+0.93j]

Sinal reconstruído (Domínio do Tempo):
[ 0.51+0.56j -0.02+0.05j  0.18-0.03j -0.09-0.05j -0.24-0.07j -0.07-0.01j
 -0.12+0.07j  0.04-0.02j]


Resolva a equação diferencial de segunda ordem $d^2y/dx^2 + y = 0$, com condições iniciais $y(0) = 1$ e $y'(0) = 0$.

In [42]:
import numpy as np
from scipy import integrate

def sistema_equacoes(x, u):
    y1 = u[0]
    y2 = u[1]

    dy1_dx = y2
    dy2_dx = -y1

    return [dy1_dx, dy2_dx]

intervalo = (0, 10)

condicoes_iniciais = [1.0, 0.0]

pontos_x = np.linspace(0, 10, 11)

resultado = integrate.solve_ivp(sistema_equacoes, intervalo, condicoes_iniciais, t_eval=pontos_x)

print("Valores de X avaliados:")
print(resultado.t)
print()

print("Resultados de Y calculados para cada X:")
print(np.round(resultado.y[0], 4))

Valores de X avaliados:
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]

Resultados de Y calculados para cada X:
[ 1.      0.5403 -0.4166 -0.9904 -0.653   0.2849  0.9609  0.753  -0.1476
 -0.9123 -0.8375]


Encontre a raiz cúbica de 27 utilizando SciPy.

In [47]:
import numpy as np
from scipy import optimize

def equacao_raiz_cubica(x):
    return (x ** 3) - 27

chute_inicial = [1.0]

resultado = optimize.fsolve(equacao_raiz_cubica, chute_inicial)

raiz_encontrada = np.round(resultado[0], 2)

print("A raiz cúbica de 27 é:")
print(raiz_encontrada)

A raiz cúbica de 27 é:
3.0


Interpole os valores de uma função $f(x) = x^2$ nos pontos $[1, 2, 3, 4, 5]$ utilizando spline cúbica.

In [46]:
import numpy as np
from scipy import interpolate

eixo_x_original = np.array([1, 2, 3, 4, 5])
eixo_y_original = eixo_x_original ** 2

interpolador_cubico = interpolate.CubicSpline(eixo_x_original, eixo_y_original)

x_denso = np.linspace(1, 5, 9)

y_calculado = interpolador_cubico(x_denso)

print("Pontos em X avaliados (originais e intermediários):")
print(np.round(x_denso, 2))
print()

print("Valores de Y correspondentes (estimados pela Spline):")
print(np.round(y_calculado, 2))

Pontos em X avaliados (originais e intermediários):
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]

Valores de Y correspondentes (estimados pela Spline):
[ 1.    2.25  4.    6.25  9.   12.25 16.   20.25 25.  ]


Realize a transformada de Fourier de um sinal discreto composto de senos e cossenos.


In [45]:
import numpy as np
from scipy import fft

quantidade_amostras = 400
taxa_amostragem = 1.0 / 100.0

tempo = np.linspace(0.0, quantidade_amostras * taxa_amostragem, quantidade_amostras, endpoint=False)

sinal_discreto = np.sin(2 * np.pi * 10 * tempo) + np.cos(2 * np.pi * 20 * tempo)

transformada = fft.fft(sinal_discreto)
frequencias = fft.fftfreq(quantidade_amostras, taxa_amostragem)

magnitudes = np.abs(transformada) * (2.0 / quantidade_amostras)

frequencias_positivas = frequencias[:quantidade_amostras//2]
magnitudes_positivas = magnitudes[:quantidade_amostras//2]

indices_picos = np.where(magnitudes_positivas > 0.5)

print("Frequências puras encontradas no sinal discreto (em Hz):")
print(np.round(frequencias_positivas[indices_picos], 2))

Frequências puras encontradas no sinal discreto (em Hz):
[10. 20.]


Resolva um sistema de equações lineares com três variáveis utilizando SciPy.

In [44]:
import numpy as np
from scipy import linalg

matriz_a = np.array([
    [1, 1, 1],
    [2, 1, -1],
    [3, -2, 1]
])

vetor_b = np.array([6, 1, 2])

resultado = linalg.solve(matriz_a, vetor_b)

valor_x = resultado[0]
valor_y = resultado[1]
valor_z = resultado[2]

print("O valor de X é:")
print(np.round(valor_x, 2))
print()

print("O valor de Y é:")
print(np.round(valor_y, 2))
print()

print("O valor de Z é:")
print(np.round(valor_z, 2))

O valor de X é:
1.0

O valor de Y é:
2.0

O valor de Z é:
3.0


Crie um DataFrame contendo as colunas Produto, Preço e Quantidade com 5 produtos

In [48]:
import pandas as pd

dados_produtos = {
    'Produto': ['Teclado', 'Mouse', 'Monitor', 'Cadeira', 'Headset'],
    'Preço': [150.00, 80.00, 800.00, 1200.00, 250.00],
    'Quantidade': [10, 25, 5, 3, 12]
}

tabela_produtos = pd.DataFrame(dados_produtos)

print("Visualizando o DataFrame:")
print()
print(tabela_produtos)

Visualizando o DataFrame:

   Produto   Preço  Quantidade
0  Teclado   150.0          10
1    Mouse    80.0          25
2  Monitor   800.0           5
3  Cadeira  1200.0           3
4  Headset   250.0          12


Leia um arquivo Excel chamado vendas.xlsx e exiba as 10 primeiras linhas.

In [49]:
import pandas as pd

tabela_vendas = pd.read_excel('vendas.xlsx')

primeiras_linhas = tabela_vendas.head(10)

print("As 10 primeiras linhas da planilha vendas.xlsx:")
print()
print(primeiras_linhas)

As 10 primeiras linhas da planilha vendas.xlsx:

   ID_Venda    Produto    Categoria  Preco_Unitario  Quantidade
0       101    Teclado  Periféricos             150           2
1       102      Mouse  Periféricos              80           5
2       103    Monitor     Hardware             800           1
3       104    Cadeira       Móveis            1200           2
4       105    Headset        Áudio             250           4
5       106   Mousepad  Periféricos              40          10
6       107     Webcam        Áudio             300           3
7       108   Notebook     Hardware            4500           1
8       109  Cabo HDMI        Cabos              45           8
9       110    Suporte       Móveis             120           4
